[INFO    ] [kivy ] :: 2023-01-27 22:02:33,939 - Factory: 190 symbols loaded
[INFO    ] [kivy ] :: 2023-01-27 22:02:34,023 - Image: Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO    ] [kivy ] :: 2023-01-27 22:02:34,055 - Window: Provider: sdl2
[INFO    ] [kivy ] :: 2023-01-27 22:02:34,542 - GL: Using the "OpenGL" graphics system
[INFO    ] [kivy ] :: 2023-01-27 22:02:34,543 - GL: GLEW initialization succeeded
[INFO    ] [kivy ] :: 2023-01-27 22:02:34,543 - GL: Backend used <glew>
[INFO    ] [kivy ] :: 2023-01-27 22:02:34,543 - GL: OpenGL version <b'4.6.14800 Compatibility Profile Context 22.5.1 30.0.15021.11005'>
[INFO    ] [kivy ] :: 2023-01-27 22:02:34,545 - GL: OpenGL vendor <b'ATI Technologies Inc.'>
[INFO    ] [kivy ] :: 2023-01-27 22:02:34,545 - GL: OpenGL renderer <b'AMD Radeon RX 6700 XT'>
[INFO    ] [kivy ] :: 2023-01-27 22:02:34,545 - GL: OpenGL parsed version: 4, 6
[INFO    ] [kivy ] :: 2023-01-27 22:02:34,545 - GL: Shading version <b'4.60'>
[INFO    ] [kivy ] :: 2023-01-27 22:02:34,545 - GL: Texture max size <16384>
[INFO    ] [kivy ] :: 2023-01-27 22:02:34,545 - GL: Texture max units <32>
[INFO    ] [kivy ] :: 2023-01-27 22:02:34,551 - Window: auto add sdl2 input provider
[INFO    ] [kivy ] :: 2023-01-27 22:02:34,552 - Window: virtual keyboard not allowed, single mode, not docked
[INFO    ] [kivy ] :: 2023-01-27 22:02:34,561 - Text: Provider: sdl2
[INFO    ] [kivy ] :: 2023-01-27 22:02:34,571 - Starting Database
[INFO    ] [kivy ] :: 2023-01-27 22:02:34,611 - GL: NPOT texture support is available
[INFO    ] [kivy ] :: 2023-01-27 22:02:34,788 - Base: Start application main loop
[INFO    ] [kivy ] :: 2023-01-27 22:02:45,193 - Creating AuthToken for jacob
[INFO    ] [kivy ] :: 2023-01-27 22:02:45,197 - Finding user
[INFO    ] [kivy ] :: 2023-01-27 22:02:45,197 - Base: Leaving application in progress...
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,197 - stderr: Traceback (most recent call last):
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,197 - stderr:   File "C:\Users\jacob\PycharmProjects\PyCalendar\main.py", line 43, in <module>
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,197 - stderr:     gui.run()
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,197 - stderr:   File "C:\Users\jacob\PycharmProjects\PyCalendar\venv\Lib\site-packages\kivy\app.py", line 956, in run
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,201 - stderr:     runTouchApp()
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,201 - stderr:   File "C:\Users\jacob\PycharmProjects\PyCalendar\venv\Lib\site-packages\kivy\base.py", line 574, in runTouchApp
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,203 - stderr:     EventLoop.mainloop()
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,203 - stderr:   File "C:\Users\jacob\PycharmProjects\PyCalendar\venv\Lib\site-packages\kivy\base.py", line 339, in mainloop
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,204 - stderr:     self.idle()
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,204 - stderr:   File "C:\Users\jacob\PycharmProjects\PyCalendar\venv\Lib\site-packages\kivy\base.py", line 383, in idle
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,204 - stderr:     self.dispatch_input()
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,204 - stderr:   File "C:\Users\jacob\PycharmProjects\PyCalendar\venv\Lib\site-packages\kivy\base.py", line 334, in dispatch_input
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,204 - stderr:     post_dispatch_input(*pop(0))
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,204 - stderr:   File "C:\Users\jacob\PycharmProjects\PyCalendar\venv\Lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,204 - stderr:     wid.dispatch('on_touch_up', me)
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,205 - stderr:   File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,205 - stderr:   File "C:\Users\jacob\PycharmProjects\PyCalendar\venv\Lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,207 - stderr:     self.dispatch('on_release')
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,207 - stderr:   File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,207 - stderr:   File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,208 - stderr:   File "kivy\_event.pyx", line 1191, in kivy._event.EventObservers._dispatch
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,208 - stderr:   File "C:\Users\jacob\PycharmProjects\PyCalendar\venv\Lib\site-packages\kivy\lang\builder.py", line 55, in custom_callback
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,209 - stderr:     exec(__kvlang__.co_value, idmap)
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,209 - stderr:   File "C:\Users\jacob\PycharmProjects\PyCalendar\gui\PyCalendar.kv", line 98, in <module>
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,209 - stderr:     on_release: root.manager.transition = SlideTransition(); root.manager.transition.direction = "up"; root.create()
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,209 - stderr:                                                                                    ^^^^^^^^^^^^^
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,209 - stderr:   File "C:\Users\jacob\PycharmProjects\PyCalendar\gui\__init__.py", line 43, in create
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,209 - stderr:     if my_db.user_exists(token.user_id):
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,210 - stderr:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,210 - stderr:   File "C:\Users\jacob\PycharmProjects\PyCalendar\data\__init__.py", line 66, in user_exists
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,210 - stderr:     print(self.get_user(user_id))
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,210 - stderr:           ^^^^^^^^^^^^^^^^^^^^^^
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,210 - stderr:   File "C:\Users\jacob\PycharmProjects\PyCalendar\data\__init__.py", line 18, in get_user
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,210 - stderr:     r = cur.execute(f"select * from Users where user_id=?", user_id)
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,210 - stderr:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[WARNING ] [kivy ] :: 2023-01-27 22:02:45,210 - stderr: sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 1, and there are 88 supplied.
